/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      fontFamily: {
        'title': ['Inter', 'system-ui', 'sans-serif'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          200: "hsl(var(--primary-200))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          900: "hsl(var(--primary-900))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          pink: {
            50: "hsl(var(--accent-pink-50))",
            100: "hsl(var(--accent-pink-100))",
            200: "hsl(var(--accent-pink-200))",
            300: "hsl(var(--accent-pink-300))",
            400: "hsl(var(--accent-pink-400))",
            500: "hsl(var(--accent-pink-500))",
            600: "hsl(var(--accent-pink-600))",
            700: "hsl(var(--accent-pink-700))",
            800: "hsl(var(--accent-pink-800))",
            900: "hsl(var(--accent-pink-900))",
          },
          purple: {
            50: "hsl(var(--accent-purple-50))",
            100: "hsl(var(--accent-purple-100))",
            200: "hsl(var(--accent-purple-200))",
            300: "hsl(var(--accent-purple-300))",
            400: "hsl(var(--accent-purple-400))",
            500: "hsl(var(--accent-purple-500))",
            600: "hsl(var(--accent-purple-600))",
            700: "hsl(var(--accent-purple-700))",
            800: "hsl(var(--accent-purple-800))",
            900: "hsl(var(--accent-purple-900))",
          },
        },
        neutral: {
          50: "hsl(var(--neutral-50))",
          100: "hsl(var(--neutral-100))",
          200: "hsl(var(--neutral-200))",
          300: "hsl(var(--neutral-300))",
          400: "hsl(var(--neutral-400))",
          500: "hsl(var(--neutral-500))",
          600: "hsl(var(--neutral-600))",
          700: "hsl(var(--neutral-700))",
          800: "hsl(var(--neutral-800))",
          900: "hsl(var(--neutral-900))",
        },
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      animation: {
        'spring-in': 'spring-in 0.6s var(--spring-bounce)',
        'float-gentle': 'float-gentle 3s ease-in-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'bubble-float': 'bubble-float 2s ease-out',
        'connection-line': 'connection-line 3s ease-in-out infinite',
        'particle-burst': 'particle-burst 1.5s ease-out forwards',
        'morph-transition': 'morph-transition 0.3s var(--spring-bounce)',
        'slide-in-right': 'slide-in-right 0.25s var(--spring-bounce)',
        'slide-in-left': 'slide-in-left 0.25s var(--spring-bounce)',
        'slide-in-up': 'slide-in-up 0.3s var(--spring-bounce)',
        'fade-in-scale': 'fade-in-scale 0.2s var(--spring-bounce)',
        'family-pulse': 'family-pulse 3s ease-in-out infinite',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.2)',
        'glass-lg': '0 12px 40px rgba(0, 0, 0, 0.15), inset 0 1px 0 rgba(255, 255, 255, 0.3)',
        'glow-sm': '0 0 20px rgba(249, 115, 22, 0.3)',
        'glow': '0 0 30px rgba(249, 115, 22, 0.4)',
        'glow-lg': '0 0 40px rgba(249, 115, 22, 0.5)',
        'premium': '0 4px 16px rgba(249, 115, 22, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.2)',
      },
      transitionTimingFunction: {
        'spring-bounce': 'var(--spring-bounce)',
        'spring-smooth': 'var(--spring-smooth)',
        'spring-gentle': 'var(--spring-gentle)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '104': '26rem',
        '112': '28rem',
        '128': '32rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      letterSpacing: {
        'tighter': '-0.05em',
        'tight': '-0.025em',
        'normal': '0em',
        'wide': '0.025em',
        'wider': '0.05em',
        'widest': '0.1em',
      },
      scale: {
        '102': '1.02',
        '98': '0.98',
      },
    },
  },
  plugins: [],
}